name: Build and deploy UniversityInformationSystem application to Azure

on: [push]

env:
  AZURE_WEBAPP_NAME: UniversityInformationSystemApp
  AZURE_WEBAPP_PACKAGE_PATH: publish
  CONFIGURATION: Release
  DOTNET_VERSION: 6.0.x
  WORKING_DIRECTORY: project

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore dependencies
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
      
      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" -c ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test "${{ env.WORKING_DIRECTORY }}" -c ${{ env.CONFIGURATION }} --no-build

      - name: Publish app for deploy
        run: dotnet publish ${{ env.WORKING_DIRECTORY }}/Presentation/Presentation.csproj -c ${{ env.CONFIGURATION }} --no-build -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy
    runs-on: windows-latest
    needs: build

    steps:
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - uses: actions/checkout@v2